version: '0.0.8'

services:
#  app:
#    container_name: app
#    image: 'mig-api:latest'
#    build:
#      dockerfile: ./docker/default/Dockerfile
#      context: .
#    expose:
#      - 8080
#    depends_on:
#      - db
#      - nginx
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mig
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#
#  db:
#    image: 'postgres:15-alpine'
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=mig
#    ports:
#      - 5432:5432

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf